# ===============
# Header
# ===============
# Navigation menu
menu:
  首页: /
  归档: /archives
# RSS link
rss: /atom.xml
# Path of title banner image of page top
banner: "images/banner.jpg"
# Subtitle of page top
subtitle:
# Header links with icon, specified links will appear at the top right corner of the page
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links:
  github: https://github.com/tutunihao

# ===============
# Content
# ===============
# "Read More" link at the bottom of excerpted articles. `false` to hide the link.
excerpt_link: 继续阅读
# Enable fancybox
fancybox: true

# ===============
# Footer
# ===============
copyright:

# ===============
# Sidebar
# ===============
# Sidebar style. You can choose `left`, `right`, `bottom` or `false`.
sidebar: right
# Widgets displaying in sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
# How many posts display in Home page.
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
# Google Analytics ID
google_analytics:
gauges_analytics:
# Favicon path
favicon: /favicon.png
# Twitter ID
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
disqus_shortname:
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  pageSize: 10
  avatar: mm
  lang: zh-cn
  placeholder: 说不定种下一颗种子，明天会长出什么来呢...
  guest_info: nick,mail,link
